### ISSUE TITLE
Repository set up

### ISSUE THREAD

**Issue by volkzayaz** [GlobBar/server#1]
1. Transfer repository from former bitbucket storage.
2. Deploy new application on DigitalOcean account. Credentials can be asked from @kostya-p-dev.
3. Resurect existing API documetnation in .xls format.

Feel free to post any questions in the issue

**Comment by kostya-p-dev** [comment]
@volkzayaz Seems like don't have possibility to edit this repository  . Please check . I am using my own repository for now.

**Comment by volkzayaz** [comment]
Done
