### ISSUE TITLE
Transaction processing crash

### ISSUE THREAD

**Issue by volkzayaz** [GlobBar/server#12]
http://107.170.102.38:9000/admin/points/transactions/

Clicking "success" on any transaction results in error 500.

Sample stacktrace here:

[SSLError at _admin_points_transactions_21_success_.html.zip](https://github.com/GlobBar/server/files/3187521/SSLError.at._admin_points_transactions_21_success_.html.zip)

**Comment by kostya-p-dev** [comment]
done
