### ISSUE TITLE
Upload media enhancement

### ISSUE THREAD

**Issue by volkzayaz** [GlobBar/server#13]
By default we now treat all uploaded photos and videos as `is_locked: true` and `price: 100`.
We need allow clients to specify this parameters upon uploading. We want dancers to choose price and decide whether the photo is locked or unlocked at all.

Introduce new parameter to requests:
POST
`report/files/`
`report/videos/`

`price: 100`///optional.

The logic is following:
if request contains `price` parameter, than photo or video should be `is_locked: true` for everybody except for photo owner. The price of the photo corresponds to `price` parameter.

if request does **NOT** contain `price` parameter, than photo or video should be `is_locked: false` for everybody.

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified
