### ISSUE TITLE
Buff up User entity

### ISSUE THREAD

**Issue by volkzayaz** [GlobBar/server#2]
1. User should have new property `balance: Integer` which represents owned money in cents.
2. Introduce new property in `GET user/me`. Current user should have `balance: Integer` in it's description.
3. Introduce temporary endpoint for topping up own account. For example `POST user/me/balance` with `{"balance": 123}` in cents.

**Comment by kostya-p-dev** [comment]
@volkzayaz  Added endPoint user**s**/me/balance/

**Comment by kostya-p-dev** [comment]
user**S**

**Comment by volkzayaz** [comment]
Done
