### ISSUE TITLE
Donate endpoint

### ISSUE THREAD

**Issue by volkzayaz** [GlobBar/server#3]
Introduce donate endpoint. User might donate money to other user from his balance.
`POST users/{id}/donate` `{ "amount": 123 }` amount is `Integer` in cents.

Upon donation application will consume part of the transaction as a fee. This fee can be configured via feature described in #4.

Restrictions:
- Reject operations if user tries to donate to himself.
- Reject operation if user has insufficient funds on his balance.

If operation succeeded, server should:
1. Add new `Message` to receiving user's feed. This message will be delivered via `GET messages/` endpoint. Title of the message "Balance update", body of the message: " `SenderUser.name` donated you x$ ".
2. Send push notification to receiver's phone with same title and body as in `Message`. For each push Server already adds `type` property into `aps` dictionary. `Type` for this push should be equal to 6.

Example test cases. Supposed fee is 5%:
- User A has 300 cents on balance. User B has 100 on his balance. User A donates 100 cents to User B. Upon competition user A would have 200 on his balance. User B would have 100 + (100 * 0.95) = 195 on his balance. User B would receive push notification and message "Balance update" "Congratulations, User A donated you 95 cents".

- User A has 300 cents. Tries to donate 301 cent to User B. Server rejects such operation.

**Comment by kostya-p-dev** [comment]
@volkzayaz  Where should 5% go ?

**Comment by kostya-p-dev** [comment]
be careful I removed id from URL and insert it to body! users/{id}/donate ->  users/donate/

**Comment by kostya-p-dev** [comment]
push Notifications still  in progress - i need device to test them.
