### ISSUE TITLE
Cash out

### ISSUE THREAD

**Issue by volkzayaz** [GlobBar/server#5]
1) API needed.
Create cash out request. Users will create it when decide to cash out funds from OnMe.
Parameters:
```
email:String /// can be different from users's email
amount: Int /// number of dollars to be deducted from balance
```
Note, upon submitting request user's balance is IMMEDIATELY, credited for requested amount.

2) Admin dashboard. Features needed:
list with active cash out requests. These requests are created by users and processed by admin.
Each request should contain:
```
    - username: String, 
    - email: String/// email for paypal transfer
    - amount: Int ////Gross value that was deducted from user
    - success button/// Request is removed from admin list. User is sent push + feed item described in part 3 of the ticket
    - error button with MANDATORY NOT NULL text field with description. Description is filled by admin/// Request is removed from admin list. User is sent push + feed item described in part 3. User gets Gross amount debited to his balance.
```
3) Upon success or error push notification + message should be generated. Structure should be identical to one described in #3.
```
"aps": {
    "type": 6,
}
```

Content for Message and push notification:
```
  "Title" : "Balance update"
  "text": "GlobBar successfully transfered you X$" /// For successful transactions, X is NET amount after fee deduction
           Admin provided description /////For unsuccessful transaction.
```
Once a day if there are new requests email reminder should be sent to jameslhg@gmail.com. Do not send emails if there are no new requests.

**Comment by kostya-p-dev** [comment]
![n2_2018-03-03 17-03-42](https://user-images.githubusercontent.com/15714195/36935804-04db1fde-1f05-11e8-84b6-7cd2dc3c2c5f.png)
![n2_2018-03-03 17-04-14](https://user-images.githubusercontent.com/15714195/36935809-0d9b80c8-1f05-11e8-9350-e499afe5386d.png)

**Comment by kostya-p-dev** [comment]
emails don't work well yet.
