### ISSUE TITLE
Separate Dancer and Fan users.

### ISSUE THREAD

**Issue by volkzayaz** [GlobBar/server#7]
Upon registration user will now choose one of two account types: Dancer and Fan.

1. All `user` entities returned from server should now have a marker: `type: Int`. 0 - fan, 1 - dancer.
2. `users/eml_register/` should receive 1 additional parameter `type: Int`, 0 - fan, 1  - dancer.
3. same for `auth/convert-token/`. Endpoint should not accept requests without `type: Int` parameter.

Updates must be reflected in the API doc

**Comment by kostya-p-dev** [comment]
@volkzayaz  done, api doc updated added tab v3

**Comment by volkzayaz** [comment]
Verified and implemented on iOS side
